###
GET http://localhost:8080/api/v1/user/test

Response: 403 Forbidden

{
  "status": 403,
  "error": "Forbidden",
  "message": "Access Denied",
  "path": "/api/v1/user/test"
}


###
GET http://localhost:8080/api/v1/user/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE2Nzg1MTQ4OTEsImV4cCI6MTY3ODU1MDg5MX0.Z_6EARyxiltfwb-OQkjm6gU6Bdh3l4XoPHvtCrVdKj8

